version: '3.8'

services:
  django:
    container_name: data_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "
            sleep 5 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8002:8000"
    depends_on:
      - db

  db:
    container_name: data_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5434:5432"
    expose:
      - 5434

volumes:
  postgres_data:
  static_volume:
  media_volume:
