# Generated by Django 5.2.6 on 2025-09-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='data.owner')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_size', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.language')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_languages', to='data.repository')),
            ],
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['createdAt'], name='data_reposi_created_c249ec_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['name'], name='data_reposi_name_3edd49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='repositorylanguage',
            unique_together={('repository', 'language')},
        ),
    ]
