# Generated by Django 5.2.6 on 2025-09-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repository',
            name='data_reposi_created_c249ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='data_reposi_name_3edd49_idx',
        ),
        migrations.AddField(
            model_name='repository',
            name='languages',
            field=models.ManyToManyField(through='data.RepositoryLanguage', to='data.language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repositorylanguage',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.repository'),
        ),
    ]
