# Generated by Django 5.2.6 on 2025-09-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_repository_data_reposi_created_c249ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
