# Generated by Django 5.2.6 on 2025-09-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_repository_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorylanguage',
            name='code_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
